version: '3.8'

services:

  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - web
      - frontend
    networks:
      - django-network  

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5      
    volumes:
      - db_data:/var/lib/mysql
      - ./todoprj/init.sql:/docker-entrypoint-initdb.d/init.sql  # 파일 경로 수정
    networks:
      - django-network

  web:
    build: ./todoprj
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./todoprj:/app
    ports:
      - "8001:3000"
    environment:
      - DEBUG=1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django-network

  frontend:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./todoprj/frontend:/home/node/app
      - ./todoprj/frontend/build:/home/node/app/build
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run build && npx serve -s build"
    networks:
      - django-network
 
volumes:
  db_data:

networks:
  django-network:
    driver: bridge

